### ISSUE TITLE
Correctly merge contexted MergeRules

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#163]
I'd like to say e.g. `jump out 2 shock` in [Eclipse](https://github.com/synkarius/caster/blob/develop/caster/apps/eclipse.py#L202-L215), but this combination does not work. 

I read [here](https://github.com/synkarius/caster/issues/156#issuecomment-235109156) that the

> CCR Merger [is] unable to correctly merge contexted MergeRules

which probably is the reason for this problem, isn't it?

**Comment by chilimangoes** [comment]
I wouldn't mind trying to look into this sometime in the next few days.

@synkarius Do you have any recommendations on where to start other than just diving into ccrmerger.py?

**Comment by synkarius** [comment]
@chilimangoes Here's a quick brain dump.

First, if you look at ccrmerger, I think the problem lies somewhere around lines 252-271:

```
        '''have base, make copies, merge in apps'''
        active_apps = []
        for rule in self._app_rules.values():
            base_copy = base.copy() if base is not None else base # make a copy b/c commands will get stripped out
            context = rule.get_context()
            mp = MergePair(time, MergeInf.APP, base_copy, rule.copy(), False, CCRMerger.specs_per_rulename(self._global_rules))
            self._run_filters(mp)
            rule = self._compatibility_merge(mp, base_copy, mp.rule2) # mp.rule2 because named_rule got copied
            rule.set_context(context)
            active_apps.append(rule)
            
        
        '''negation context for appless version of base rule'''
        contexts = [rule.get_context() for rule in self._app_rules.values() \
                    if rule.get_context() is not None]# get all contexts
        negation_context = None
        for context in contexts:
            negate = ~context
            if negation_context is None: negation_context = negate
            else: negation_context & negate
```

What I'm attempting to do here is, take a copy of the "base" rule, meaning the combined CCR rule up to this point in the building process, and make one copy of it per contexted rule. Then I try to negate its Context in the main "base" rule (the use-everywhere-except-this-app rule). So if there were just Eclipse, we'd end up with:
base (context = not-eclipse)
base + eclipse (context = eclipse)
If there were Eclipse and Notepad++, we'd get:
base (context = not-eclipse, not-npp)
eclipse (context = eclipse)
npp (context = npp)
... and so forth.

My temporary solution was to remove the Eclipse rules from the CCR merger entirely. 
```
if settings.SETTINGS["apps"]["eclipse"]:
#     if settings.SETTINGS["miscellaneous"]["rdp_mode"]:
#         control.nexus().merger.add_global_rule(EclipseRule())
#         control.nexus().merger.add_global_rule(EclipseCCR())
#     else:
#         control.nexus().merger.add_app_rule(EclipseCCR(), context)
        
        rule = EclipseRule(name="eclipse")
        gfilter.run_on(rule)
        ccr = EclipseCCR()
        gfilter.run_on(ccr)
        grammar.add_rule(rule)
        grammar.add_rule(ccr)
        grammar.load()
```

Perhaps a better temporary solution would be to give EclipseCCR a `pronunciation` attribute (distinct) from "eclipse" and add it back in by default.

Also of note: Eclipse has its own "jump in" command which is different from the generic asynchronous "jump in" which doesn't handle the number parameter.

**Comment by kendonB** [comment]
@LexiconCode/@Danesprite do you know of the top of your head if there's a modern approach to address this long-standing issue now that we have seen a lot of development of Dragonfly?

**Comment by LexiconCode** [comment]
This should be taken care of in the CCRMerger rewrite,
