### ISSUE TITLE
Consider command mapping by accent

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#233]
I have made many changes to the standard commands in caster, some of which might be useful for others with a New Zealand accent.

As a new accented user, it would be nice to have a set of commands that fit one's accent.

Is DPI15's deep learning good enough that this is a non-issue for the new users of today?

I think it would just be a matter of a setting that activates a set of Rules just like they were in /user.

**Comment by LexiconCode** [comment]
In order to get robust accuracy based on accent/microphone/sound card everyone tweaks their grammars a little bit. DPI15 has been a sizable improvement but I definitely don't think it's a replacement for phonetically distinct commands customize per accent. 

[Simplified Filter Rules](http://caster.readthedocs.io/en/latest/caster/doc/readthedocs/CCR/#rule-filters-simplified)
[Rule Filters](http://caster.readthedocs.io/en/latest/caster/doc/readthedocs/examples/rules/Caster%20Rules/#how-rule-filters-work)

There's two main schools of thought on how to create grammars that exist on a spectrum. 
On the far right keeping the command vocabulary directly tied to the function. That means very literal command phrase that is closely tied to the commands function. Commands that the user expects to say to produce the desired result.

The spectrum goes from literal to phonetically distinct leans towards ambiguous phrasing on the far left.
The  right side of the spectrum because it's literal tied to the action it reduce cognitive load because the lines closest to what the user expects the command action to execute.

 The advantages of approach is significant lower cognitive load making the grammars easier to picked up if their standardized. The same can be said for the alphabet or numerics.

- Beginning end of spectrum `go forward`, letter 'a' one '1'
- Middle spectrum is a lesser representation 'get forward',  Alpha 'a', num '1'
- Far end is phonetically distinct 'bop dash' , arc 'a', pound '1' 

The right side of spectrum leads to an overall loss of accuracy due to decreased phonetic distinctness which is further complicated by accents. This is also compounded by the type of audio equipment and sound quality produced. Therefore the need to create phonetically distinct phrases that fit a person's accent and audio setup.

I've often wondered if caster would benefit for adoption if things would be more literal right-sided approach even though there's decreased accuracy but the cognitive load would be less. From there people would then make phonetically distinct changes that fit their environment and preferences.

I'm in favor of the idea of creating filter profiles that cater to each of the spectrums as they could be distributed with caster. Although we would need to find a way to automate generating documentation to keep everything up to date.

The other advantage of distributing filter profiles is it helps users see how to implement their own customizations without changing the source code as well.

**Comment by gerrish** [comment]
I actually had an Idea about the documentation. I was thinking about a Tool which will produce a read me from grammars by using the description off the mappings. Combined with special comments or conventions in the way descriptions are written which would allow for grouping Together voice commands according to their use.

This would make it very easy to create documentation for new grammars and to keep the documentation always updated. The readmes produced would also be in markdown so that they would be easily readable in github.
If this is something you would like, I will create a new issue.

**Comment by LexiconCode** [comment]
@kendonB what are your thoughts?

Would you mind creating a Rule Filters for some of your customizations. You can start off small and add to it as you see fit. We can use that for testing as we develop profiles.

**Comment by kendonB** [comment]
I'm starting this and the first change I'm trying to make is changing "fly lease" to "laib". Since this is a combo command, I'm guessing the simplified rule filter isn't clever enough to deal with it. It it possible to make those sorts of customizations work through the simplified rule filter interface?

**Comment by LexiconCode** [comment]
@kendonB thanks for looking into that. 'ascii' codec. Could you upload your example? 
We've been updating to Unicode looks like we need to take a look at the filter roles.

We need test units for filter rules @Versatilus

**Comment by LexiconCode** [comment]
The bug and filter rules can now be tracked and discussed here.  https://github.com/synkarius/caster/issues/236. Thanks for the bug report!

Until this bug is fixed continuing on with filter rules is on hold. In order to keep the thread clean I might hide your bug report? Let me know if you can still see it though I've never hidden a post before.

**Comment by LexiconCode** [comment]
@kendonB #236. is now resolved! With your permission I'd like to clean up this thread removing or minimizing the troubleshooting. That way we can focus on the topic and it's easier for anyone in coming to follow.

Let's see what we can come up with!

**Comment by kendonB** [comment]
I think this point is best solved by people sharing their `.caster` folders and advertising their accent, rather than by caster. I will push for this once it's a bit easier to make all customizations via `.caster` rather than the source.
