### ISSUE TITLE
Moving the ccr folder out of /lib

### ISSUE THREAD

**Issue by mrob95** [dictation-toolbox/Caster#325]
The folder structure doesn't seem to make a lot of sense at the moment, with a very un-clear distinction made between command modules and back-end definitions. I think the simplest thing to do would be to:

* Move the caster/lib/ccr folder into caster/, so that it's in the same place as caster/apps. These are really the two folders which users are going to want to tinker with on a daily basis.
* Move the caster/asynch folder into caster/lib. Nobody is ever going to need to touch this.
* **Maybe** move the ccr/core folder into the main caster/ directory as well? This would make the three main caster functions - language modules, core navigation and context dependent commands - obvious and separate.

Thoughts?

**Comment by LexiconCode** [comment]
I would agree all three points as it make sense.

**Comment by mrob95** [comment]
Okay, I've done it on mine and got it working (after quite a few error messages :-)) but it might be worth clearing the pull request schedule before doing this one, as it's going to make anything else unmergeable.

**Comment by comodoro** [comment]
If shuffling directories, I could maybe suggest debate about
- renaming `async` to something specific, e.g. isn't it all GUI?
- `recording` is not all CCR (or all recording)
- loading of CCR and apps rules in `_caster.py` might be more readable than currently via `__init__.py` in `ccr/` and `apps/`
- I have no opinion about the `core` dir (perhaps slightly in favor of keeping it in `ccr/` because these are in fact CCR rules), but having core rule names hardwired in class CCRMerger feels wrong

**Comment by LexiconCode** [comment]
I would be in favor of keeping the   the core file in the CCR directory. I would also keep the structure for loading CCR has it is. In the future we will change how this works or eliminate it altogether that way it doesn't CCR files don't have to be registered.

**Comment by mrob95** [comment]
Currently aiming to move the ccr and asynch folders once #312 has been merged if there are no objections

**Comment by Danesprite** [comment]
@mrob95 I should have the work on that finished soon :-)
