### ISSUE TITLE
odd error trying to get Sikuli to work on a new computer

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/Caster#455]
I see the java window pop up, stay black for a few seconds, then the following displays immediately before the window disappears:

```
[error] script [ xmlrpc_server ] stopped with error at line --unknown--
[error] Error caused by: java.lang.NullPointerException
```

I transferred everything over to another computer which works. Any help troubleshooting?

**Comment by LexiconCode** [comment]
Java version might be relevant in this case. It might be something to look over on team viewer we can coordinator schedules.

**Comment by LexiconCode** [comment]
Here's the documentation related to running sikulix commandline[sikulix](https://sikulix-2014.readthedocs.io/en/latest/faq/010-command-line.html)

Try running your sikulix commands outside of caster via command line and see if any errors are produced. You can include commandline flags for debugging purposes.

**Comment by kendonB** [comment]
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

I am able to run "click" just fine using the Sikuli IDE.

**Comment by kendonB** [comment]
I had changes the sikuli locations in `settings.toml` but is it possible that there's another reference to the old location that gets used somewhere?

**Comment by kendonB** [comment]
Is there any way for me to step through the `xmlrpc_server` file?

**Comment by LexiconCode** [comment]
> I had changes the sikuli locations in `settings.toml` but is it possible that there's another reference to the old location that gets used somewhere?

Not that I know of, It should get all its information for file paths from  `settings.toml`.

> Is there any way for me to step through the `xmlrpc_server` file?

So the 20 second version is this. I use PyCharm with the PyDev plugin for remote debugging. (I'm quite certain that other editors can also do this.) Then, I temporarily insert the following two lines in the Caster source code near where I'd like to debug:

```
import pydevd
pydevd.settrace("localhost", port=5678)

```
Then I restart Dragon. And then after that point in the code execution, breakpoints work. It's called "remote debugging". It's a little different than normal debugging b/c you are not running the code with the same process you're debugging it with. (Dragon runs the code, the IDE has the debugging server.)

The debugging process is also simple if you use Windows speech recognition because a stack is simpler without Dragon or Natlink.

**Comment by LexiconCode** [comment]
This is a bit of a shot of dark but try adding system variable path. `SIKULI_HOME`
and include the path to your SikuliX install. `C:\SikuliX `

**Comment by LexiconCode** [comment]
This may be related to an upstream bug https://github.com/RaiMan/SikuliX1/issues/111

> The script worked perfectly if running by using IDE. Just failed when running with argument "-r"

**Comment by LexiconCode** [comment]
Go to `C:\Users\User\.caster\sikuli`
open command prompt and execute the following taking into account your SikuliX install path `C:\SikuliX\SikuliX_1.1.4\sikulix.jar` and SikuliX script name `click.sikuli`

`java -jar C:\SikuliX\SikuliX_1.1.4\sikulix.jar -v -r click.sikuli`

**Comment by kendonB** [comment]
This works great for me: `java -jar C:\SikuliX\SikuliX_1.1.4\sikulix.jar -v -r click.sikuli`

I will also try changing the environment variable

**Comment by kendonB** [comment]
Working now, except the clicks are in the wrong place on the screen... not sure why. I don't know if this was the original problem but the combination of java update, sikuli update, and reverting some buggy changes in the user code got it to go.
