### ISSUE TITLE
Update filter/user rules documentation

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#513]
Example user rule in the user space:
```Python
from dragonfly import Text
from castervoice.lib.dfplus.merge.mergerule import MergeRule
from castervoice.lib.dfplus.state.short import R

class Decker(MergeRule):
    pronunciation = "decker"

    mapping = {
        "hit the deck": R(Text("shipwrecked"))
    }

def get_rule():
    return Decker()
```

`get_rule` creates global grammars instance `Decker`  rule . The `Decker` rule needs to be enabled by voice for example say `enable decker`.

So get_rule for rules. The same goes for get_filter for filters.
.py files in ~/.caster/rules require a get_rule method. .py files in ~/.caster/filters require a get_filter method.

**Comment by mrob95** [comment]
I think we can probably get rid of the `get_rule` thing entirely and just import the rules as normal with `control.nexus.merger`

**Comment by LexiconCode** [comment]
> I think we can probably get rid of the `get_rule` thing entirely and just import the rules as normal with `control.nexus.merger`

The change to `get_rule` is to simplify the process for the average user and and to check for `get_rule` implementation providing feedback to the end-user.  Obviously these things could be discussed but that was the intent anyway of `get_rule`. For advanced users which we could include in the documentation as well `control.nexus.merger`

**Comment by seekM** [comment]
I think it's a bit confusing to have different ways to add rules / filters depending on whether you are in `.caster` or in `Caster`. I think if an average user wants to create a custom rule he will probably also check how rules are created in `Caster`, because he knows them already and wants to see how certain commands are implemented. He'll then see how rules are loaded there, wonder why it's different and be confused. That's what happend to me. Therefore I see a disadvantage rather than an advantage in this regard.

What feedback can be provided to the end-user if `get_rule` is used that can't be provided otherwise?

I think if we go for the `get_rule` approach a few things should be adjusted:
- It was said in the gitter chat that `get_rule` doesn't work with `App Context`. [This](https://github.com/seekM/.caster/blob/master/rules/thunderbird.py#L66-L72) is how I do it at the moment, bypassing `get_rule`
- At the moment it is not required to have the `get_rule` method in filter files. E.g. [this](https://github.com/seekM/.caster/blob/master/filters/filter.py) is a filter file I use, which uses `control.nexus().merger.add_filter()` two times to add two filtes. Is it possible to add two filters using `get_rule`?

**Comment by LexiconCode** [comment]
Part of the confusion was created due to a lack of documentation on the change. Eventually will get to the place where they won't have to look at the source code in order to change or add to a grammar.

> What feedback can be provided to the end-user if get_rule is used that can't be provided otherwise?
Right now it checks if it's been implemented provides feedback to the user. Further checks could be added easily whereas it would not with our standard implementation.

I definitely agree with those two adjustments

**Comment by mrob95** [comment]
I think it's important for the implementation which we expect users to use to be the same as the implementation which is used in the default rules. 

One solution which simplifies the adding of rules while not creating multiple methods and leading to confusion would be to create some wrapper functions in `control` which would look like:
```
def global_rule(rule):
    nexus().merger.add_global_rule(rule)
```

And then adding a rule would be done with:
```
control.global_rule(MyRule())
```

Which is slightly less verbose

**Comment by LexiconCode** [comment]
Transformers have now been relegated to only simple transformers a.k.a. words.txt in the 1.0.0 rewrite. Closing
