### ISSUE TITLE
Record from history doesn't work with non-ascii characters

### ISSUE THREAD

**Issue by seekM** [dictation-toolbox/Caster#546]
`Record from history` doesn't work with non-ascii characters. Error output:
```
Record From History
action: Exception from function record_from_history:
Traceback (most recent call last):
  File "C:\dev\Python27\lib\site-packages\dragonfly\actions\action_function.py", line 136, in _execute
    self._function(**arguments)
  File "C:\dev\Natlink-User\Caster\castervoice\lib\ccr\recording\history.py", line 36, in record_from_history
    h_launch.launch(settings.QTYPE_RECORDING, data=formatted)
  File "C:\dev\Natlink-User\Caster\castervoice\asynch\hmc\h_launch.py", line 28, in launch
    Popen(instructions)
  File "C:\dev\Python27\Lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\dev\Python27\Lib\subprocess.py", line 644, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 243: ordinal not in range(128)
action.exec: Execution failed: Function(record_from_history): 'ascii' codec can't encode character u'\xfc' in position 243: ordinal not in range(128)
```
Is this Caster or dragonfly related?

**Comment by seekM** [comment]
The problem seems to be that [Popen](https://github.com/dictation-toolbox/Caster/blob/develop/castervoice/asynch/hmc/h_launch.py#L28) can't handle unicode characters by default in Python 2.x

**Comment by comodoro** [comment]
Looks like the partial workaround is `mbcs` encoding: https://stackoverflow.com/a/48466893/999198. Other is calling directly the OS `CreateProcess` function

**Comment by comodoro** [comment]
To fix this is actually not a problem, since recent history gets sent to the history window via command line, so we can encode it however we like. But while debugging it it seemed that there are problems either in Dragonfly or in Natlink with mimicking words with non-ASCII chars, curiously even windows-1252 ones ("Düsseldorf"). If @Danesprite could chime in, he is the resident expert. So we can show these words, but what to do with them, if they cannot be used?

Incidentally, even specs cannot use these characters, am I missing something? There are plenty of accented English words.

**Comment by Danesprite** [comment]
@comodoro Well this issue is clearly caused by an encoding issue somewhere because "Düsseldorf" is mimicked perfectly if using `unicode` objects instead (e.g. with `Mimic(u"Düsseldorf")`). It is definitely a dragonfly issue rather than a caster or natlink one. A similar problem can also occur with the `Text` action in Python 3 if the Unicode keyboard option is enabled.

I think there are still a few things like this in dragonfly from getting most of the library working in Python 3. I'll see if I can track these down and fix them.

**Comment by comodoro** [comment]
It seems like one was a Caster issue - adding reference to extra even when the extra was not declared in the specification - although how this could have caused an encoding issue, and nothing else, is beyond me. But I have another encoding problem, some English words cannot be in specs - I will make an issue.
