### ISSUE TITLE
Syntax error still breaks everything (actually breaks more stuff than before)

### ISSUE THREAD

**Issue by alexboche** [dictation-toolbox/Caster#684]
This is about the rewrite ccrmerger2 @synkarius 

**Describe the bug**
Introducing a syntax error does not do anything until you reboot Dragon at which point all of caster is broken and fixing the syntax error does not have any effect until you reboot dragon again. Previously, syntax errors would break certain commands but not all for example "reboot dragon" would still work. Now no commands work.

**To Reproduce**
In synkarius/ccrmerger2, say "enable visual studio code continuous". Insert a new line at line 17 of vscode.py: `"baller": Key("e"),` . After waiting a few seconds, test that saying "baller"  presses the "e" button.  Then introduce a syntax error by changing line 17 to `"baller":Key("e")d,`. Test that the command "baller" still works. Then reboot Dragon. You should see that no caster commands work. Correct the syntax error by changing line 17 back to `"baller": Key("e"),`. Save the file and weight a few seconds. You should see that no caster commands work (including "reboot dragon"). After (manually) rebooting Dragon again, everything should be working.

**Expected behavior**
I don't know what the expected behavior is supposed to be. I thought maybe there was going to be protection from syntax errors breaking all the commands, but maybe that's just for instant reloadability and not for when you reboot dragon?

**Comment by synkarius** [comment]
This is definitely a bug. Broken rules should be ignored on load, not crash the system. I will look at this tonight.

**Comment by synkarius** [comment]
@alexboche This fix makes it such that rules which are broken at boot do not get loaded -- which means that you cannot fix them and have them hot reload while Dragon is running. However, they no longer crash the system.

Also FYI, as of this rewrite, rules which get broken AFTER boot time (during hot-reloading) will continue to work in their pre-broken state until they are fixed in a way which lets them get reloaded without errors.

I realize that it would be nice to be able to fix rules which are broken at boot time, but I did not target that capability in this rewrite. You are correct to point out though, that boot time crashes should not end up worse off than they were before, and I believe this fix should take care of that.

**Comment by alexboche** [comment]
> You are correct to point out though, that boot time crashes should not end up worse off than they were before, and I believe this fix should take care of that.

This appears to be working.
