### ISSUE TITLE
A generic method to reboot voice recognition backend.

### ISSUE THREAD

**Issue by ghost** [dictation-toolbox/Caster#77]
Although WSR as much easier to manually restart then DNS it still lacks the voice command to do so. It would be nice to extend the restart dns script to WSR. It should be simple to implement as caster process needs to be terminated. Then restart  _caster.py.

**Comment by synkarius** [comment]
This is a good idea, but I think it would be handled better by a separate batch file.

**Comment by Zone22** [comment]
True I was thinking we could have one command that works for both WSR and DNS.

**Comment by Versatilus** [comment]
I think three batch scripts would work better. One each for Dragon and WSR,
and one that resets both. The separation could prove useful.

**Comment by Zone22** [comment]
I assume the first batch script would determine which which voice recognition application is active then trigger the appropriate application-specific reboot script?

**Comment by Versatilus** [comment]
I was thinking about three batch scripts for three separate voice commands:
"reboot Dragon", "reboot WSR", and "reboot speech".

**Comment by Zone22** [comment]
Sounds like a plan. What would 'reboot speech' do?

**Comment by Zone22** [comment]
I'm close to implementing this. I'm not sure how [this](https://github.com/synkarius/caster/blob/master/caster/apps/dragon.py#L46-L51) bit of code functions. Normally this would be the place were the executable name and window title would be defined. As Dragon and WSR don't have window titles I assume that's why it's different than all the other supported apps. If I'm reading it right it's a global commands set. 

What would WSR equivalent be that disables Dragon.py when loaded?

**Comment by synkarius** [comment]
You are correct that if you don't define the window title or executable, the command set becomes global. All you have to do is flip the boolean in your version.

    if settings.WSR:

Don't worry about disabling Dragon when running from WSR. If you're running WSR, the Dragon commands should already be inactive.

**Comment by Zone22** [comment]
Thank you for the tip. The Dragon reboot command that's been re-factored works expected.

WRS triggers its own reboot bat file but does nothing. In the caster CMD window that shows the reboot script executing with the correct file paths. 

[u'D:/NatLink/NatLink/MacroSystem/caster/bin/reboot_wsr.bat', u'"D:/NatLink/NatLink/MacroSystem/caster_caster.py"']
No handlers could be found for logger "action"

There are two ways to functionally restart caster.  
1. The first is to close Python.exe killing caster but leaving WSR running. Then restart _caster.py
2. The second is to close Python.exe killing caster and WSR. Then restart _caster.py

The first method is preferable because 2. exasperates [issue 68](https://github.com/synkarius/caster/issues/68) this leads me to believe that caster initializes before WSR is properly initialized.

For testing purposes my latest commit should close Windows speech recognition ''sapisvr.exe"
Feel free to test but at least [take a look](https://github.com/Zone22/caster/commit/77aff1f8ad6cbbb3d16aea0c4965608d28769d33). Otherwise I'm stumped.

**Comment by synkarius** [comment]
You're correct in thinking that #68 is caused by Caster starting before WSR does. I also agree that option 1 is preferable. 

Just to be clear, which part is giving you trouble-- stopping Caster or restarting it? If it's the stopping that's giving you trouble, might I suggest an alternate route? Why not just stop the loop at the bottom of _caster.py? Put in a conditional break statement or something. If it's the restarting part, you appear to have a typo in your Caster path:

    D:/NatLink/NatLink/MacroSystem/caster_caster.py

should be

    D:/NatLink/NatLink/MacroSystem/caster/_caster.py

**Comment by Zone22** [comment]
Restarting was an a problem but the issue is obvious. I see, BASE_PATH only within the 'caster' folder not high enough within the folder structure for  '_caster'. I'll have to do a little research to set up a conditional break statement. :P

**Comment by Zone22** [comment]
Well I can't edit the BASE_PATH to go higher because the user might put 'caster' into any folder when using WSR. Conversely if they use Dragon we could always assume that folder name would be "MacroSystem". Thoughts?

**Comment by chilimangoes** [comment]
@Zone22 I'm not sure exactly what you're trying to do, but can't you just use ".." with BASE_PATH to get the parent directory? For example, I believe that `SETTINGS["paths"]["BASE_PATH"] + ".."` would return "C:\NatLink\NatLink\MacroSystem\" if you're running caster under DNS.

**Comment by Zone22** [comment]
@chilimangoes 
Your correct I'm trying get to the parent directory of BASE_PATH were I can execute _caster.py.
   "CASTER_PATH", SETTINGS["paths"]["BASE_PATH"] + ".." + "_caster.py"
returns
  "CASTER_PATH": "D:/NatLink/NatLink/MacroSystem/caster.._caster.py"

**Comment by chilimangoes** [comment]
@Zone22 Sorry, my bad. It should be something like `SETTINGS["paths"]["BASE_PATH"] + "/../" + "_caster.py"`. (I don't remember for sure whether Python on Windows handles forward slashes in paths, but I think it does.)

**Comment by Zone22** [comment]
@synkarius 
Even though it prints the that it launched the bat file nothing happens. I can get the .bat stop Python.exe or restart _caster even though it has the correct file path. The issue that I'm experiencing is documented by the new entry in [#63](https://github.com/synkarius/caster/issues/63)?

**Comment by synkarius** [comment]
@Zone Regarding stopping Caster, what I meant about the conditional break statement was to have some boolean tied to both a command and the main loop (in _caster.py), which is on by default (and keeps the loop running) and is shut off by the command (which causes the loop to terminate). Something like this:

    ( ... in your wsr command file, which I'm calling "wsr.py" for this example ... )
    
    RUN = True

Import that file ("wsr") in the imports section of _caster.py. Then instead of having the WSR loop condition as

    while true:

you can change it to

    while wsr.RUN:

and terminating is done by writing a command like

    def terminate():
        global RUN
        RUN = False
    
    ( ... then in your MappingRule ... )
    
    "terminate speech recognition":           R(Function(terminate)),

As for restarting it, I think @chilimangoes is on the money, but I don't have time to test it tonight. I'll do so tomorrow.

**Comment by synkarius** [comment]
@Zone22 , @Versatilus - You guys still interested in this?

**Comment by Zone22** [comment]
I am. As soon as things settle down from the move I will resume work on this.

**Comment by chilimangoes** [comment]
You know, that batch script that @Versatilus provided has worked really well for me, but I've been thinking. The Windows Speech API might provide a fairly easy way to create a small standalone app that runs in the background and listens for a single command to reboot Dragon and/or WSR. This would (I think) get around the issue of not being able to reboot Dragon by voice command when it's frozen. I could probably whip up a POC of this in C# fairly easily.

**Comment by Zone22** [comment]
@chilimangoes by all means if you've got something like that planned go-ahead. Sounds fabulous!

**Comment by synkarius** [comment]
@chilimangoes's background app idea is better than what I just pushed, but these are a just-for-now.
